name: solar system workflow
on:
  push:
    branches: ["main", "feature/*"]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' #the link connection to database
  #(mongodb+srv://> the type of connection) (supercluster>the name of server/cluster) (/superdata > the name of database ) 
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit_testing:
    strategy:
      matrix:
        nodejs_version: [20]
        os: [ubuntu-latest]
        # exclude: # here i say i donot want the nodejs_version: 19 run with os macos-latest
        # - nodejs_version: 19
        #   os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node-js version - ${{ matrix.nodejs_version}}
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.nodejs_version }}
      - name: install npm # npm(node package manager )
        run: npm install
      - name: unit_testing
        id: test-job
        run: npm test
      - name: archive test result 
        if: always()
        #if: steps.test-job.outcome == 'failure'|| steps.test-job.outcome == 'success' #here i say if the step (unit_testing) 
        #fail or pass the job (archive test result) will continue and upload the artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Mocha-Test-Result
          path: test-result.xml
  
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: check code coverage
        run: npm run coverage
        continue-on-error: true
      - name: archive coverage result
        if: always()  
        uses: actions/upload-artifact@v6.0.0
        with:
          name: code-coverage-Result
          path: coverage
          retention-days: 5 #the duration  in days after that duration the artifact will be deleted
  docker:
    needs: [code-coverage , unit_testing]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: build
        uses: docker/build-push-action@v6.18.0
        with:
          context: . #this is where the docker  file located
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system-test:${{ github.sha }}
      
      - name: docker image test
        run: |
          docker images
          docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_URI=$MONGO_USERNAME \
          -e MONGO_PASSWORD=$MONGO_PASSWORD \
          ${{ vars.DOCKERHUB_USERNAME }}/solar-system-test:${{ github.sha }}
          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP

          echo testing image url using wget
          wget -q -O - 127.0.0.1:3000/live | grep live