name: solar system workflow
on:
  push:
    branches: ["main", "feature/*"]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system-test:${{ github.sha }}

jobs:
  unit_testing:
    strategy:
      matrix:
        nodejs_version: [20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node-js version - ${{ matrix.nodejs_version}}
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.nodejs_version }}
      - name: install npm
        run: npm install
      - name: unit_testing
        id: test-job
        run: npm test
      - name: archive test result 
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Mocha-Test-Result
          path: test-results.xml
  
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: check code coverage
        run: npm run coverage
        continue-on-error: true
      - name: archive coverage result
        if: always()  
        uses: actions/upload-artifact@v6.0.0
        with:
          name: code-coverage-Result
          path: coverage
          retention-days: 5

  docker:
    needs: [code-coverage , unit_testing]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: build
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
      - name: docker image test
        run: |
          docker images
          docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_URI=$MONGO_URI \
          -e MONGO_USERNAME=$MONGO_USERNAME \
          -e MONGO_PASSWORD=$MONGO_PASSWORD \
          ${{ env.DOCKER_IMAGE }}
          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP
          echo testing image url using wget
          wget -q -O - 127.0.0.1:3000/live | grep live

  terraform:
    needs: [docker]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Validate
        run: terraform validate 
      - name: terraform plan
        id: plan
        run: terraform plan 
      - name: terraform apply 
        run: terraform apply --auto-approve

  deploy:
        needs: terraform
        name: deploy to EKS
        runs-on: ubuntu-latest

        steps:
            - name: checkout config files
              uses: actions/checkout@v4


            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: updat kubeconfig
              run: | 
                    aws eks  update-kubeconfig \
                      --region us-east-1 \
                      --name final-project_eks \

            - name: Trigger app deployment
              uses: statsig-io/kubectl-via-eksctl@main
              env:
                 aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 region: us-east-1
                 cluster: final-project_eks


            - name: Deploy  k8s deployments
              run: |
               kubectl apply -f deployment.yml 
               kubectl apply -f service.yml 
              working-directory: k8s

            - name: Verify Deployment
              run: |
                kubectl get pods  
                kubectl get svc
